--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_imperial_kessel = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_imperial_kessel", weight = 10000000},
	}
}

addLootGroupTemplate("space_imperial_kessel", space_imperial_kessel)