--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_blacksun_tier4 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_blacksun_tier1", weight = 1666666},
		{groupTemplate = "ship_component_blacksun_tier2", weight = 1666666},
		{groupTemplate = "ship_component_blacksun_tier3", weight = 1666666},
		{groupTemplate = "ship_component_blacksun_tier4", weight = 3333333},
		{groupTemplate = "ship_component_blacksun_tier5", weight = 1666669},
	}
}

addLootGroupTemplate("space_blacksun_tier4", space_blacksun_tier4)
