--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_rebel_kessel = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_rebel_kessel", weight = 10000000},
	}
}

addLootGroupTemplate("space_rebel_kessel", space_rebel_kessel)