--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_rebel_tier4 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_rebel_tier1", weight = 1666666},
		{groupTemplate = "ship_component_rebel_tier2", weight = 1666666},
		{groupTemplate = "ship_component_rebel_tier3", weight = 1666666},
		{groupTemplate = "ship_component_rebel_tier4", weight = 3333333},
		{groupTemplate = "ship_component_rebel_tier5", weight = 1666669},
	}
}

addLootGroupTemplate("space_rebel_tier4", space_rebel_tier4)
