--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_merchant_tier3 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_merchant_tier1", weight = 2000000},
		{groupTemplate = "ship_component_merchant_tier2", weight = 2000000},
		{groupTemplate = "ship_component_merchant_tier3", weight = 4000000},
		{groupTemplate = "ship_component_merchant_tier4", weight = 2000000}
	}
}

addLootGroupTemplate("space_merchant_tier3", space_merchant_tier3)
