--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_rebel_tier3 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_rebel_tier1", weight = 2000000},
		{groupTemplate = "ship_component_rebel_tier2", weight = 2000000},
		{groupTemplate = "ship_component_rebel_tier3", weight = 4000000},
		{groupTemplate = "ship_component_rebel_tier4", weight = 2000000}
	}
}

addLootGroupTemplate("space_rebel_tier3", space_rebel_tier3)
