--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_trade_fed_tier5 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_trade_fed_tier2", weight = 2000000},
		{groupTemplate = "ship_component_trade_fed_tier3", weight = 2000000},
		{groupTemplate = "ship_component_trade_fed_tier4", weight = 2000000},
		{groupTemplate = "ship_component_trade_fed_tier5", weight = 4000000}
	}
}

addLootGroupTemplate("space_trade_fed_tier5", space_trade_fed_tier5)
