--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_imperial_tier1 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_imperial_tier1", weight = 6666666},
		{groupTemplate = "ship_component_imperial_tier2", weight = 3333334}
	}
}

addLootGroupTemplate("space_imperial_tier1", space_imperial_tier1)
