--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_valarian_tier2 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_valarian_tier1", weight = 2500000},
		{groupTemplate = "ship_component_valarian_tier2", weight = 5000000},
		{groupTemplate = "ship_component_valarian_tier3", weight = 2500000}
	}
}

addLootGroupTemplate("space_valarian_tier2", space_valarian_tier2)
