--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_hutt_tier3 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_hutt_tier1", weight = 2000000},
		{groupTemplate = "ship_component_hutt_tier2", weight = 2000000},
		{groupTemplate = "ship_component_hutt_tier3", weight = 4000000},
		{groupTemplate = "ship_component_hutt_tier4", weight = 2000000}
	}
}

addLootGroupTemplate("space_hutt_tier3", space_hutt_tier3)
