--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ship_component_imperial_kessel = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "arm_kessel_imperial_rendili_crystalline_durasteel", weight = 416820},
		{itemTemplate = "arm_kessel_imperial_sds_imperial_impervious", weight = 416660},
		{itemTemplate = "arm_kessel_imperial_sfs_imperial_finest", weight = 416660},
		{itemTemplate = "bst_kessel_imperial_cygnus_hyperthrust", weight = 416660},
		{itemTemplate = "bst_kessel_imperial_sds_experimental_b7", weight = 416660},
		{itemTemplate = "bst_kessel_imperial_sfs_ultra_thrust", weight = 416660},
		{itemTemplate = "ddi_kessel_imperial_cygnus_dp44", weight = 416660},
		{itemTemplate = "ddi_kessel_imperial_sds_unknown_prototype", weight = 416660},
		{itemTemplate = "ddi_kessel_imperial_sfs_imperial_finest", weight = 416660},
		{itemTemplate = "eng_kessel_imperial_rendili_hyperion_drive", weight = 416660},
		{itemTemplate = "eng_kessel_imperial_sds_special_forces", weight = 416660},
		{itemTemplate = "eng_kessel_imperial_sfs_special_forces", weight = 416660},
		{itemTemplate = "rct_kessel_imperial_kdy_powermaster", weight = 416660},
		{itemTemplate = "rct_kessel_imperial_sds_secret_ops", weight = 416660},
		{itemTemplate = "rct_kessel_imperial_sfs_special_forces", weight = 416660},
		{itemTemplate = "shd_kessel_imperial_cygnus_experimental_system", weight = 416660},
		{itemTemplate = "shd_kessel_imperial_sds_secret_ops", weight = 416660},
		{itemTemplate = "shd_kessel_imperial_sfs_megapolyweb", weight = 416660},
		{itemTemplate = "wpn_kessel_imperial_rendili_prototype_x", weight = 416660},
		{itemTemplate = "wpn_kessel_imperial_sds_experimental_secret_ops", weight = 416660},
		{itemTemplate = "wpn_kessel_imperial_sfs_elite_ops", weight = 416660},
		{itemTemplate = "cap_kessel_imperial_rendili_hyperbattery", weight = 416660},
		{itemTemplate = "cap_kessel_imperial_sds_imperial_finest", weight = 416660},
		{itemTemplate = "cap_kessel_imperial_sfs_array", weight = 416660},
	}
}

addLootGroupTemplate("ship_component_imperial_kessel", ship_component_imperial_kessel)