--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ship_component_rebel_kessel = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "arm_kessel_rebel_mandal_corrugated_plastisteel", weight = 416820},
		{itemTemplate = "arm_kessel_rebel_slayn_flexsteel_multilayer", weight = 416660},
		{itemTemplate = "arm_kessel_rebel_sorosuub_spidershell_plating", weight = 416660},
		{itemTemplate = "bst_kessel_rebel_incom_quicksilver", weight = 416660},
		{itemTemplate = "bst_kessel_rebel_incom_windrunner", weight = 416660},
		{itemTemplate = "bst_kessel_rebel_mandal_lightning_m1", weight = 416660},
		{itemTemplate = "ddi_kessel_rebel_incom_dx61", weight = 416660},
		{itemTemplate = "ddi_kessel_rebel_incom_supreme_interface", weight = 416660},
		{itemTemplate = "ddi_kessel_rebel_qualdex_integrated_array", weight = 416660},
		{itemTemplate = "eng_kessel_rebel_incom_t11_elite", weight = 416660},
		{itemTemplate = "eng_kessel_rebel_novaldex_blackhole_elite", weight = 416660},
		{itemTemplate = "eng_kessel_rebel_novaldex_grb1138", weight = 416660},
		{itemTemplate = "rct_kessel_rebel_incom_overdriven_elite", weight = 416660},
		{itemTemplate = "rct_kessel_rebel_mandal_modified_gorax", weight = 416660},
		{itemTemplate = "rct_kessel_rebel_slayn_high_output_experimental", weight = 416660},
		{itemTemplate = "shd_kessel_rebel_incom_rayshield_overdriver", weight = 416660},
		{itemTemplate = "shd_kessel_rebel_sorosuub_ion_mesh_projection", weight = 416660},
		{itemTemplate = "shd_kessel_rebel_unknown_proton_interweave_system", weight = 416660},
		{itemTemplate = "wpn_kessel_rebel_incom_dualcore_flashcannon", weight = 416660},
		{itemTemplate = "wpn_kessel_rebel_riiz_combine_slammer_cannon", weight = 416660},
		{itemTemplate = "wpn_kessel_rebel_unknown_rayslinger", weight = 416660},
		{itemTemplate = "cap_kessel_rebel_armek_array", weight = 416660},
		{itemTemplate = "cap_kessel_rebel_deepwell_k33_prototype", weight = 416660},
		{itemTemplate = "cap_kessel_rebel_taim_hypercharger", weight = 416660},
	}
}

addLootGroupTemplate("ship_component_rebel_kessel", ship_component_rebel_kessel)