--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_hortrix_steelarm_quest = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "space_palace_access_doc", weight = 10000000}
	}
}

addLootGroupTemplate("space_hortrix_steelarm_quest", space_hortrix_steelarm_quest)