--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_tatooine_blacksun = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_blacksun_tier1", weight = 3333333},
		{groupTemplate = "ship_component_blacksun_tier2", weight = 3333334},
		{itemTemplate = "space_loot_tatooine_blacksun", weight = 1666666},
		{itemTemplate = "space_loot_tatooine_blacksun2", weight = 1666667}
	}
}

addLootGroupTemplate("space_story_tatooine_blacksun", space_story_tatooine_blacksun)