--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_dantooine_slave = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_pirate_tier1", weight = 2500000},
		{groupTemplate = "ship_component_pirate_tier2", weight = 2500000},
		{groupTemplate = "ship_component_pirate_tier3", weight = 2500000},
		{itemTemplate = "space_loot_dantooine_slave", weight = 2500000}
	}
}

addLootGroupTemplate("space_story_dantooine_slave", space_story_dantooine_slave)