--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_endor_artisan = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_merchant_tier1", weight = 2000000},
		{groupTemplate = "ship_component_merchant_tier2", weight = 2000000},
		{groupTemplate = "ship_component_merchant_tier3", weight = 2000000},
		{groupTemplate = "ship_component_merchant_tier4", weight = 2000000},
		{itemTemplate = "space_loot_endor_artisan", weight = 1000000},
		{itemTemplate = "space_loot_endor_artisan2", weight = 1000000}
	}
}

addLootGroupTemplate("space_story_endor_artisan", space_story_endor_artisan)