--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_naboo_civspeeder = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_civilian_tier1", weight = 3333333},
		{groupTemplate = "ship_component_civilian_tier2", weight = 3333333},
		{itemTemplate = "space_loot_naboo_civspeeder", weight = 3333334}
	}
}

addLootGroupTemplate("space_story_naboo_civspeeder", space_story_naboo_civspeeder)