--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_dantooine_junk = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_merchant_tier1", weight = 2500000},
		{groupTemplate = "ship_component_merchant_tier2", weight = 2500000},
		{groupTemplate = "ship_component_merchant_tier3", weight = 2500000},
		{itemTemplate = "space_loot_dantooine_junk", weight = 833333},
		{itemTemplate = "space_loot_dantooine_junk2", weight = 833333},
		{itemTemplate = "space_loot_dantooine_junk3", weight = 833334}
	}
}

addLootGroupTemplate("space_story_dantooine_junk", space_story_dantooine_junk)