--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_all_freighter = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "space_loot_all_freighter", weight = 1250000},
		{itemTemplate = "space_loot_all_freighter_2", weight = 1250000},
		{itemTemplate = "painting_nebula_flower", weight = 1250000},
		{itemTemplate = "painting_schematic_transport_ship", weight = 1250000},
		{itemTemplate = "painting_zabrak_m", weight = 1250000},
		{itemTemplate = "painting_zabrak_f", weight = 1250000},
		{itemTemplate = "painting_tato_s04", weight = 1250000},
		{itemTemplate = "painting_fighter_pilot_human_01", weight = 1250000},
	}
}

addLootGroupTemplate("space_story_all_freighter", space_story_all_freighter)