--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_dantooine_warren = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_imperial_tier1", weight = 2500000},
		{groupTemplate = "ship_component_imperial_tier2", weight = 2500000},
		{groupTemplate = "ship_component_imperial_tier3", weight = 2500000},
		{itemTemplate = "space_loot_dantooine_warren", weight = 2500000}
	}
}

addLootGroupTemplate("space_story_dantooine_warren", space_story_dantooine_warren)