--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_tatooine_hutt = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_hutt_tier1", weight = 3333333},
		{groupTemplate = "ship_component_hutt_tier2", weight = 3333333},
		{itemTemplate = "space_loot_tatooine_hutt", weight = 3333334}
	}
}

addLootGroupTemplate("space_story_tatooine_hutt", space_story_tatooine_hutt)