--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_series_tinrilo = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_pirate_tier1", weight = 2500000},
		{groupTemplate = "ship_component_pirate_tier2", weight = 2500000},
		{groupTemplate = "ship_component_pirate_tier3", weight = 2500000},
		{itemTemplate = "space_loot_tatooine_series_tinrilo", weight = 833333},
		{itemTemplate = "space_loot_naboo_series_tinrilo", weight = 833333},
		{itemTemplate = "space_loot_endor_series_tinrilo", weight = 833334}
	}
}

addLootGroupTemplate("space_story_series_tinrilo", space_story_series_tinrilo)