--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

space_story_dantooine_rebel = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{groupTemplate = "ship_component_rebel_tier1", weight = 2500000},
		{groupTemplate = "ship_component_rebel_tier2", weight = 2500000},
		{groupTemplate = "ship_component_rebel_tier3", weight = 2500000},
		{itemTemplate = "space_loot_dantooine_rebel", weight = 1250000},
		{itemTemplate = "space_loot_dantooine_rebel2", weight = 1250000}
	}
}

addLootGroupTemplate("space_story_dantooine_rebel", space_story_dantooine_rebel)